#pragma once

#include "opcode.hpp"

/**
 * @brief A single bytecode instruction executed by the Virtual Machine.
 *
 * An Instruction represents one operation that the VM can perform.
 * It consists of:
 *
 * - An opcode that identifies the operation.
 * - An optional operand that provides additional data required by
 *   the operation.
 *
 * Examples:
 *
 *     PUSH_LITERAL 3
 *     PUSH_LITERAL 7
 *     ADD
 *     PRINT
 *
 * In the examples above:
 *
 *     Opcode: PUSH_LITERAL
 *     Operand: 3
 *
 *     Opcode: PUSH_LITERAL
 *     Operand: 7
 *
 *     Opcode: ADD
 *     Operand: 0 (unused)
 *
 *     Opcode: PRINT
 *     Operand: 0 (unused)
 *
 * Operands are interpreted according to the opcode.
 *
 * For example:
 *     PUSH_LITERAL 3
 *
 * means:
 *     Load constants[3] onto the VM stack.
 *
 * while:
 *     JUMP 15
 *
 * means:
 *     Continue execution at instruction 15.
 *
 * Instructions are generated by the Compiler and stored inside
 * a Chunk. During execution, the VM reads each Instruction using
 * its Instruction Pointer (IP) and performs the requested operation.
 */
struct Instruction
{
    /**
     * @brief Operation to be executed by the VM.
     */
    OpCode opcode;

    /**
     * @brief Additional data required by the opcode.
     *
     * The meaning of this value depends on the opcode.
     *
     * Examples:
     *
     *     PUSH_LITERAL 5
     *                  ^
     *                operand
     *
     *     JUMP 12
     *          ^^
     *          operand
     */
    uint32_t operand = 0;
};
